version: "3.8"

services:
  react:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react
    tty: true
    volumes:
      - ./react-app:/app/react
    command: "yarn start"
    ports:
      - 3000:3000
    networks:
      - golang_test_network

  go:
    container_name: go
    build:
      context: ./golang
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./mysql/.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./golang/src
        target: /go/src
    networks:
      - golang_test_network

  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    volumes:
      - type: volume
        source: mysql_test_volume
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
    networks:
      - golang_test_network

  nginx:
    build: ./nginx
    ports:
      - "1234:1234"
    depends_on:
      - "go"
    networks:
      - golang_test_network

volumes:
  mysql_test_volume:
    name: mysql_test_volume

networks:
  golang_test_network:
    external: true
